django/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('movies/', views.movies, name='movies'),
    path('joint_movies/', views.joint_movies, name='joint_movies'),
    path('actors/', views.actors, name='actors'),
    path('separation/', views.separation, name='separation'),
    path('graphexp/', views.graphexp, name='graphexp'),
]

django/polls/views.py
from __future__  import print_function  # Python 2/3 compatibility
from gremlin_python import statics
from gremlin_python.structure.graph import Graph
from gremlin_python.process.graph_traversal import __
from gremlin_python.process.strategies import *
from gremlin_python.driver.driver_remote_connection import DriverRemoteConnection

from django.shortcuts import render


def index(request):
    context = {'action': 'show'}
    return render(request, 'polls/index.html', context)


def movies(request):
    graph = Graph()
    remoteConn = DriverRemoteConnection('ws://<path to neptune>:8182/gremlin','g')
    g = graph.traversal().withRemote(remoteConn)
    #print(g.V().limit(2).toList())
    myList = g.V().has('name', request.POST['actor_name']).out().limit(40).values().toList()
    remoteConn.close()
    context = {'actor': request.POST['actor_name'], 'movies': myList}
    return render(request, 'polls/movie-results.html', context)


def joint_movies(request):
    statics.load_statics(globals())
    inputs = [x.strip() for x in request.POST['actor_names'].split(',')]
    graph = Graph()
    remoteConn = DriverRemoteConnection('ws://<path to neptune>:8182/gremlin','g')
    g = graph.traversal().withRemote(remoteConn)
    #print(g.V().limit(2).toList())
    if (len(inputs) == 2) :
        myList = g.V().has('name',inputs[0]).repeat(out().where(__.in_().has('name',inputs[1]))).emit().values().toList()
    else :
        myList = g.V().has('name',inputs[0]).repeat(out().where(__.in_().has('name',inputs[1])).where(__.in_().has('name',inputs[2]))).emit().values().toList()

    remoteConn.close()
    #print(myList)
    context = {'actor': request.POST['actor_names'], 'movies': myList}
    return render(request, 'polls/movie-results.html', context)


def actors(request):
    graph = Graph()
    remoteConn = DriverRemoteConnection('ws://<path to neptune>:8182/gremlin','g')
    g = graph.traversal().withRemote(remoteConn)
    myList = g.V().has('title', request.POST['movie_name']).in_().limit(40).values().toList()
    remoteConn.close()
    context = {'movie': request.POST['movie_name'], 'actors': myList}
    return render(request, 'polls/movie-results.html', context)

def separation(request):
    statics.load_statics(globals())
    inputs = [x.strip() for x in request.POST['actor_names'].split(',')]
    graph = Graph()
    remoteConn = DriverRemoteConnection('ws://<path to neptune>:8182/gremlin','g')
    g = graph.traversal().withRemote(remoteConn)
    myList = g.V().has('name',inputs[0]).repeat(out().in_().simplePath()).until(has('name',inputs[1])).path().by('name').by('title').limit(40).toList()
    remoteConn.close()
    context = {'actors': request.POST['actor_names'], 'separation': myList}
    return render(request, 'polls/movie-results.html', context)


def graphexp(request):
    context = {'action': 'show'}
    return render(request, 'polls/graphexp.html', context)

django/polls/templates/polls/index.html
<h2>Actors and movies</h2>
<form action="{% url 'polls:movies' %}" method="post">
{% csrf_token %}
  Enter an actor whose movies you want to see: <input type="text" name="actor_name"><br/>
  <input type="submit" value="Submit">
</form>

<p></p>
<form action="{% url 'polls:joint_movies' %}" method="post">
{% csrf_token %}
  Enter all actors (2 or 3, comma separated) whose common movies you want to see: <input type="text" name="actor_names">
<br/>
  <input type="submit" value="Submit">
</form>

<p></p>
<form action="{% url 'polls:actors' %}" method="post">
{% csrf_token %}
  Enter a movie whose actors you want to see: <input type="text" name="movie_name"><br/>
  <input type="submit" value="Submit">
</form>


<p></p>
<form action="{% url 'polls:separation' %}" method="post">
{% csrf_token %}
  Enter any two actors (comma separated) and find the degrees of separation between them: <input type="text" name="actor_names"><br/>
  <input type="submit" value="Submit">
</form>

django/polls/templates/polls/movie-results.html
{% if actor %}
    <p> {{ actor }} acted in (limit 40):</p>
    <ul>
    {% for movie in movies %}
        <li>{{ movie }}</li>
    {% endfor %}
    </ul>

{% elif movie %}
    <p> {{ movie }} has the following actors (limit 40):</p>
    <ul>
    {% for actor in actors %}
        <li>{{ actor }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p> {{ actors }} have the following connections (limit 40):</p>
    <ul>
    {% for sep in separation %}
        <li>{{ sep }}</li>
    {% endfor %}
    </ul>
{% endif %}